[package]
name = "ray"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.33.2"

[dev-dependencies]
argh = "0.1.13"
gif = "0.13.1"
gltf = "1.4.1"
image = { version = "0.25.6", default-features = false, features = ["tiff"] }
rayon = "1.10.0"

